export const SET_LATEST_TWEET = 'SET_LATEST_TWEET';
export const SET_IS_MOBILE = 'SET_IS_MOBILE';
export const SET_EMAIL_SENDER = 'SET_EMAIL_SENDER';
export const SET_EMAIL_MESSAGE = 'SET_EMAIL_MESSAGE';
export const SET_EMAIL_RESPONSE = 'SET_EMAIL_RESPONSE';
export const SET_PROJECT_ANIMATION = 'SET_PROJECT_ANIMATION';